### ISSUE TITLE
Train / Test Validation

### ISSUE THREAD

**Issue by SadiqJafferSaleh** [iterativv/NostalgiaForInfinity#100]
Suggest to use different period (unseen data while Train) for Test the strategy progress , changes , Tuning ,etc .. .  
This will ensure the result is generalized and not over fitted .

To track , you can add both train result and Test result .. If the result is high in train(Data/Period) and very low in test(Data/Period) that's means not apply thing changes ... .....

Thanks all for contributions and good luck

**Comment by eSeR1805** [comment]
Not sure what you're talking about. We're not doing any 'training' or hyperopting. As for the development process we use multiple pairs, timeranges and exchanges to backtest and validate

**Comment by SadiqJafferSaleh** [comment]
then how do you tune parameters ?

**Comment by eSeR1805** [comment]
By focusing on bad/suboptimal trades. You debug the buy/sell conditions and see it it can be improved without hurting others.

**Comment by SadiqJafferSaleh** [comment]
mmmmmm ..
I have better Idea , where I can find full log about all trades with their triggered parameters (Sales and buy) in order to optimize them ?

**Comment by eSeR1805** [comment]
https://www.freqtrade.io/en/latest/backtesting/
https://www.freqtrade.io/en/latest/hyperopt/
We've moved away from hyperopting, we're at the point where taking counscious decisions about parameters is far better than just chugging parameter combinations and hoping.
