### ISSUE TITLE
Wiki - Community at Discord

### ISSUE THREAD

**Issue by m1cmac** [iterativv/NostalgiaForInfinity#116]
Hi,
is this link https://discord.gg/75afDh4tpu still valid? 
It's from https://github.com/iterativv/NostalgiaForInfinity/wiki

I'm still getting **_Invalid invitation_** error.. .

BR,
M.

**Comment by eSeR1805** [comment]
Updated Discord to a perma invite link

**Comment by Govind-S-B** [comment]
ah sorry I thought I fixed it
