### ISSUE TITLE
problem with undefined pta

### ISSUE THREAD

**Issue by GoshaGrek** [iterativv/NostalgiaForInfinity#120]
hi everybody
got a problem with undefined pta
using docker, installed and reinstalled already

13 00:30:29,328 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error name 'pta' is not defined calling <bound method IStrategy._analyze_ticker_internal of <NostalgiaForInfinityNext.NostalgiaForInfinityNext object at 0x7f6aac671af0>>

freqtrade | Traceback (most recent call last):

freqtrade | File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper

freqtrade | return f(*args, **kwargs)

freqtrade | File "/freqtrade/freqtrade/strategy/interface.py", line 454, in _analyze_ticker_internal

freqtrade | dataframe = self.analyze_ticker(dataframe, metadata)

freqtrade | File "/freqtrade/freqtrade/strategy/interface.py", line 433, in analyze_ticker

freqtrade | dataframe = self.advise_indicators(dataframe, metadata)

freqtrade | File "/freqtrade/freqtrade/strategy/interface.py", line 798, in advise_indicators

freqtrade | return self.populate_indicators(dataframe, metadata)

freqtrade | File "/freqtrade/user_data/strategies/NostalgiaForInfinityNext.py", line 4552, in populate_indicators

freqtrade | informative_1h = self.informative_1h_indicators(dataframe, metadata)

freqtrade | File "/freqtrade/user_data/strategies/NostalgiaForInfinityNext.py", line 4179, in informative_1h_indicators

freqtrade | informative_1h['cti'] = pta.cti(informative_1h["close"], length=20)

freqtrade | NameError: name 'pta' is not defined

freqtrade | 2021-09-13 00:30:29,330 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair XLM/USDT: name 'pta' is not defined

freqtrade | 2021-09-13 00:30:29,352 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair XRP/USDT

freqtrade | 2021-09-13 00:30:29,361 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair RVN/USDT

freqtrade | 2021-09-13 00:30:29,368 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair XLM/USDT

Hope you have any ideas
pandas_ta, pandas-ta already installed

**Comment by GoshaGrek** [comment]
hi everybody
got a problem with undefined pta
using docker, installed and reinstalled already



**13 00:30:29,328 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error name 'pta' is not defined calling <bound method IStrategy._analyze_ticker_internal of <NostalgiaForInfinityNext.NostalgiaForInfinityNext object at 0x7f6aac671af0>>**

freqtrade  | Traceback (most recent call last):

freqtrade  |   File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper

freqtrade  |     return f(*args, **kwargs)

freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 454, in _analyze_ticker_internal

freqtrade  |     dataframe = self.analyze_ticker(dataframe, metadata)

freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 433, in analyze_ticker

freqtrade  |     dataframe = self.advise_indicators(dataframe, metadata)

freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 798, in advise_indicators

freqtrade  |     return self.populate_indicators(dataframe, metadata)

freqtrade  |   File "/freqtrade/user_data/strategies/NostalgiaForInfinityNext.py", line 4552, in populate_indicators

freqtrade  |     informative_1h = self.informative_1h_indicators(dataframe, metadata)

freqtrade  |   File "/freqtrade/user_data/strategies/NostalgiaForInfinityNext.py", line 4179, in informative_1h_indicators

freqtrade  |     informative_1h['cti'] = pta.cti(informative_1h["close"], length=20)

freqtrade  | NameError: name 'pta' is not defined

freqtrade  | 2021-09-13 00:30:29,330 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair XLM/USDT: name 'pta' is not defined

freqtrade  | 2021-09-13 00:30:29,352 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair XRP/USDT

freqtrade  | 2021-09-13 00:30:29,361 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair RVN/USDT

freqtrade  | 2021-09-13 00:30:29,368 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair XLM/USDT

Hope you have any ideas
pandas_ta, pandas-ta already installed

**Comment by eSeR1805** [comment]
So how are we to debug this? How exactly did you install pandas? Obviously that's still the issue here

**Comment by GoshaGrek** [comment]
![image](https://user-images.githubusercontent.com/22540587/133077902-37628a1e-2200-4c50-ad6b-b99f7959ddeb.png)
this way

**Comment by eSeR1805** [comment]
Not a user myself but looks like this needs to be done through Docker specific config:
https://github.com/iterativv/NostalgiaForInfinity/wiki/Preliminary-Setup#nfi-deployment
