### ISSUE TITLE
VolumePairList is duplicated in pairlist-volume-binance-busd.json and pairlist-volume-binance-usdt.json

### ISSUE THREAD

**Issue by bandrade** [iterativv/NostalgiaForInfinity#134]
Not sure if that is intentional, but I see https://github.com/iterativv/NostalgiaForInfinity/blob/main/configs/pairlist-volume-binance-busd.json#L29-L33 and https://github.com/iterativv/NostalgiaForInfinity/blob/main/configs/pairlist-volume-binance-usdt.json#L29-L33 duplicated. 

Since it's not indented, I'd like to check whether it should be fixed or not. Please close if don't, thank you.

Thank you

**Comment by Govind-S-B** [comment]
The second volume filter makes sure that only 50 pairs are there after the initial filter . So yeah the bot get top 70 , applies filters and then from them choose top 50 as its final pair list
