### ISSUE TITLE
typo in NextGen row 2527

### ISSUE THREAD

**Issue by hippocritical** [iterativv/NostalgiaForInfinity#135]
elif 0.02 > current_profit >= 0.01:
                    if (last_candle['rsi_14'] < 39.0) and (last_candle['cmf'] < -0.25):
                        return True, 'sell_profit_p_bull_48_2_2_1'

should be sell_profit_p_bull_48_2_1_1

**Comment by iterativv** [comment]
Fixed, thanks.
