### ISSUE TITLE
Strategy breaks when trying to load 1h informative indicators

### ISSUE THREAD

**Issue by HankHoneymoon** [iterativv/NostalgiaForInfinity#143]
Ubuntu 21.04
Using Freqtrade's Docker image
Running this strategy is profitable for a few days, then it breaks and fills the logfile with "unable to load candle data" notifications for each individual symbol. 

`Exception: input_arrays parameter missing required data key: ema1
freqplus     | 2021-10-23 01:19:34,347 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair CELO/USDT: input_arrays parameter missing required data key: ema1
freqplus     | 2021-10-23 01:19:34,348 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error input_arrays parameter missing required data key: ema1 calling <bound method IStrategy._analyze_ticker_internal of <NostalgiaForInfinityV7.NostalgiaForInfinityV7 object at 0x7f120254c7c0>>
freqplus     | Traceback (most recent call last):
freqplus     |   File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
freqplus     |     return f(*args, **kwargs)
freqplus     |   File "/freqtrade/freqtrade/strategy/interface.py", line 494, in _analyze_ticker_internal
freqplus     |     dataframe = self.analyze_ticker(dataframe, metadata)
freqplus     |   File "/freqtrade/freqtrade/strategy/interface.py", line 473, in analyze_ticker
freqplus     |     dataframe = self.advise_indicators(dataframe, metadata)
freqplus     |   File "/freqtrade/freqtrade/strategy/interface.py", line 845, in advise_indicators
freqplus     |     return self.populate_indicators(dataframe, metadata)
freqplus     |   File "/freqtrade/user_data/strategies/NostalgiaForInfinityV7.py", line 1558, in populate_indicators
#freqplus     |     informative_1h = self.informative_1h_indicators(dataframe, metadata)  #######THERE IS AN ERROR HERE
freqplus     |   File "/freqtrade/user_data/strategies/NostalgiaForInfinityV7.py", line 1388, in informative_1h_indicators
#freqplus     |     informative_1h['ema_12'] = ta.EMA(informative_1h, timeperiod=12) ########ALSO AN ERROR HERE.
freqplus     |   File "talib/_abstract.pxi", line 398, in talib._ta_lib.Function.__call__
freqplus     |   File "talib/_abstract.pxi", line 270, in talib._ta_lib.Function.set_function_args
freqplus     |   File "talib/_abstract.pxi", line 221, in talib._ta_lib.Function.set_input_arrays
freqplus     | Exception: input_arrays parameter missing required data key: ema1`

Then it loses candle data;

`freqplus     | 2021-10-23 01:19:34,762 - freqtrade.strategy.interface - WARNING - Outdated history for pair CELO/USDT. Last tick is 1109 minutes old
freqplus     | 2021-10-23 01:19:34,767 - freqtrade.strategy.interface - WARNING - Outdated history for pair AAVE/USDT. Last tick is 1109 minutes old
freqplus     | 2021-10-23 01:19:34,771 - freqtrade.strategy.interface - WARNING - Outdated history for pair HBAR/USDT. Last tick is 1109 minutes old
`

Thanks for your hard work and I appreciate any insight you can give me.

**Comment by eSeR1805** [comment]
Could be anything between freqtrade and exchange. There's not enough info here for a conclusion. Is this still occuring?
