### ISSUE TITLE
Add Exchange

### ISSUE THREAD

**Issue by TheSarfaraz** [iterativv/NostalgiaForInfinity#148]
Kindly add for support of the new exchange x.woo.org

**Comment by Govind-S-B** [comment]
this should be an issue made at ccxt or freqtrade repo , NFI is just a strategy made for freqtrade . If you meant for blacklists and pairlists , we dont have enough people using those exchanges . Most people using the strategy uses binance.com or kucoin , only a tiny fraction of people use other exchanges and it will not be realistically possible to maintain support for literally all of them
