### ISSUE TITLE
idea: log NFI version in the freqtrade logs on start

### ISSUE THREAD

**Issue by ipetko96** [iterativv/NostalgiaForInfinity#160]
It would be very useful to know which version is actually used.
Or is there any other way how to check it?
I am running FT in container.

**Comment by Govind-S-B** [comment]
As of now there is no way to check it other than cross referencing the strategy file with the released version or commits from the repo . There was a feature suggestion on the freqtrade repo for an additional information in telegram showing a strategy version along with freqtrade version . Xmathias decided it was not worthwhile and pointed out that it may cause other potential bugs
