### ISSUE TITLE
non-technical description of the sell signals.

### ISSUE THREAD

**Issue by berapp** [iterativv/NostalgiaForInfinity#168]
Is there somewhere to find a generalized summation of the sell signals?  Just basic stuff like will NFIX ever sell at a loss?  I know it doesn't use freqtrade's stoploss, but does it have on in it's own stoploss signals?  Does it have any ROI signals?

**Comment by eSeR1805** [comment]
Yes for all questions except the first one.

**Comment by berapp** [comment]
Thanks
