### ISSUE TITLE
[Question] Apply the supertrend indicator for sell and buy

### ISSUE THREAD

**Issue by KaanRF** [iterativv/NostalgiaForInfinity#177]
Hi, 
It can be already existed because I have seen some "atr" based calculations but I wanted to hear your opinions. How it could positively effect if we can apply the supertrend indicator while populate of the sell and buy. 

[Supertrend from tradingview](https://www.tradingview.com/support/solutions/43000634738-supertrend/#:~:text=Definition,direction%20and%20to%20position%20stops.)

**Comment by eSeR1805** [comment]
It's just a trend detection tool. Quite heavy in terms of compute time. We're aware of it but probably won't be included as we have other means to do the same.
