### ISSUE TITLE
PerformanceWarning

### ISSUE THREAD

**Issue by andesma04** [iterativv/NostalgiaForInfinity#189]
NostalgiaForInfinityX.py:8957: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe['tpct_change_12']  = self.top_percent_change(dataframe,12)

**Comment by mkajnar** [comment]
Hello,

I have the same problems with latest version

/freqtrade/user_data/strategies/NostalgiaForInfinityX.py  on  line **8958 and line 8966** too

Thanks for solving. :)

Milan

**Comment by zlov137** [comment]
9110 and 10024 here

**Comment by eSeR1805** [comment]
It's just a warning
