### ISSUE TITLE
sell_over_main signal name and variable naming mismatch

### ISSUE THREAD

**Issue by koradiyakaushal** [iterativv/NostalgiaForInfinity#19]
https://github.com/iterativv/NostalgiaForInfinity/blob/main/NostalgiaForInfinityNext.py#L2055

Example:(take from above line number)

elif (self.sell_custom_profit_11.value > current_profit > self.sell_custom_profit_10.value):
      if (last_candle['rsi'] < self.sell_custom_rsi_10.value) & (last_candle['ema_25'] < last_candle['ema_50']):
          return True, 'signal_profit_10'

here, signal calculation is for 10, but used sell_custom_profit_11 in it. is it still right?
same happened with below signal_profit calculations

**Comment by iterativv** [comment]
Nice catch! I'll fix it ASAP.

**Comment by iterativv** [comment]
However, it's because I start counting from zero and not 1. I probably should change that not to cause confusion.

**Comment by iterativv** [comment]
However, note that the check is between two values, greater than 10 and less than 11, in your example. And so on.

**Comment by eSeR1805** [comment]
Sell logic was changed so I think this was solved.
