### ISSUE TITLE
Update from v11.0.64 ERROR DataFrame

### ISSUE THREAD

**Issue by ThunderBRZ** [iterativv/NostalgiaForInfinity#190]
After update my from v11.0.64 to above 11.0.85 i see this 

/freqtrade/user_data/strategies/NostalgiaForInfinityX.py:8990: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe['tpct_change_144'] = self.top_percent_change(dataframe,144)
/freqtrade/user_data/strategies/NostalgiaForInfinityX.py:8998: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe['live_data_ok'] = (dataframe['volume'].rolling(window=72, min_periods=72).min() > 0)
/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py:1667: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  self.obj[key] = value

**Comment by eSeR1805** [comment]
/freqtrade/user_data/strategies/NostalgiaForInfinityX.py:8990: Performance**Warning**

**Comment by ThunderBRZ** [comment]
Sorry for this, strategie works fine with this warning. 

Thank´s so much.
