### ISSUE TITLE
Question for currency change

### ISSUE THREAD

**Issue by seungy0** [iterativv/NostalgiaForInfinity#207]
https://github.com/iterativv/NostalgiaForInfinity/pull/206/commits/2054deb3d28f50768a1047f754c91c1f0888be5e#diff-a1f6deca42bbe5158119f3c47ee31e8011987b625326d5212716964e245bbc2d

From what I understand, I think you're referring to the BTC exchange rate for the strategy.
I'm going to trade in KRW. Is there any problem if I change the code like this? Will this work properly?

**Comment by iterativv** [comment]
It can work with any stake. You can do that, if there are pairs for that stake.
