### ISSUE TITLE
NostalgiaForInfinity install?

### ISSUE THREAD

**Issue by traxtrax29** [iterativv/NostalgiaForInfinity#213]
Hello,

Im new to Freqtrade, really not a coder or anything. However I managed to install Freqtrade a few days ago and its fun to tweak and play around with some strategies.
After checking the NostalgiaForInfinity strategy I really want to try this strategy for my backtestings.
However when I copy pasted the this strategy into my strategy folder, im getting an error whenever I try to do a backtesting

 The MoniGoMani Configuration filenames could not be loaded from".hurry"... Please run "python3 ./mgm-hurry setup" to create your ".hurry" file
2022-03-10 23:59:57,331 - freqtrade.exchange.exchange - INFO - Closing async ccxt session.

I installed all the other requirements. But I dont know how to solve this error.
Can anyone help me out with this error.

Your help would be greatly appreciated!

**Comment by mkavinkumar1** [comment]
Remove other strategies in that folder

**Comment by traxtrax29** [comment]
Thanks!
That worked :)

**Comment by KaanRF** [comment]
> Thanks! That worked :)

good, then please close the issue :)
