### ISSUE TITLE
NostalgiaForInfinityX will not foward test..help

### ISSUE THREAD

**Issue by Mayhem-Tv** [iterativv/NostalgiaForInfinity#228]
hello, I can back test fine. but when i attempt to forward test i get this error.

freqtrade-bot01 | usage: freqtrade [-h] [-V]
freqtrade-bot01 |                  {trade,create-userdir,new-config,new-strategy,download-data,convert-data,convert-trade-data,trades-to-ohlcv,list-data,backtesting,backtesting-show,edge,hyperopt,hyperopt-list,hyperopt-show,list-exchanges,list-markets,list-pairs,list-strategies,list-timeframes,show-trades,test-pairlist,convert-db,install-ui,plot-dataframe,plot-profit,webserver}
freqtrade-bot01 |                  ...
freqtrade-bot01 | freqtrade: error: unrecognized arguments: NostalgiaForInfinityX
freqtrade-bot01 exited with code 2

**Comment by Mayhem-Tv** [comment]
ok not an install problem. Ive started my system from scratch and got this

Starting freqtrade ... done
Attaching to freqtrade
freqtrade    | usage: freqtrade [-h] [-V]
freqtrade    |                  {trade,create-userdir,new-config,new-strategy,download-data,convert-data,convert-trade-data,trades-to-ohlcv,list-data,backtesting,backtesting-show,edge,hyperopt,hyperopt-list,hyperopt-show,list-exchanges,list-markets,list-pairs,list-strategies,list-timeframes,show-trades,test-pairlist,convert-db,install-ui,plot-dataframe,plot-profit,webserver}
freqtrade    |                  ...
freqtrade    | freqtrade: error: unrecognized arguments: NostalgiaForInfinityX
freqtrade    | usage: freqtrade [-h] [-V]
freqtrade    |                  {trade,create-userdir,new-config,new-strategy,download-data,convert-data,convert-trade-data,trades-to-ohlcv,list-data,backtesting,backtesting-show,edge,hyperopt,hyperopt-list,hyperopt-show,list-exchanges,list-markets,list-pairs,list-strategies,list-timeframes,show-trades,test-pairlist,convert-db,install-ui,plot-dataframe,plot-profit,webserver}
freqtrade    |                  ...
freqtrade    | freqtrade: error: unrecognized arguments: NostalgiaForInfinityX
freqtrade exited with code 2

**Comment by iterativv** [comment]
This is too old already. If there are still issue, please, don't hesitate to open a new issue.
