### ISSUE TITLE
Optimize win rate

### ISSUE THREAD

**Issue by naujoks-stefan** [iterativv/NostalgiaForInfinity#232]
First of all, top strategy!!!

Think the win rate could be optimized by trading days ( Mon - Fri ). I have made the experience that BTC usually drops sharply on Saturday / Sunday and thus the rest is also pulled down. A purchase on Saturday is very risky. With me now this weekend TWT and MANA happened. Is at this moment at -4.4% and -5.7%. 

Is it possible for you adding this as parameter feature in next versions?

Best
Stefan

**Comment by iterativv** [comment]
Hi. Those are normal. We can't expect always to buy and move right away higher. A little patience, I think it's all fine.

**Comment by naujoks-stefan** [comment]
Thank you for your fast answer.

I keep my fingers crossed. 

Best
Stefan
