### ISSUE TITLE
Consideration of existing coins

### ISSUE THREAD

**Issue by naujoks-stefan** [iterativv/NostalgiaForInfinity#233]
I hope I'm posting right here. 
I have the following problem and don't know how to solve it. The bot is running great with your strategy! The bot buys and sells according to your strategy with profit. But I have a coin that was bought through strategy and I already had some of this coin on binance. I assumed that this would be taken into account in the calculation... do you have a solution? Fraqtrade shows the right sum of this coin at startup ( bought by strategy + existence ).

Best Stefan

**Comment by iterativv** [comment]
Hi. Well, it's not doable. You can edit the database, of course, but that is tedious.

I'd suggest to just put a sell limit on exchange and simply wait for it to sell for USDT (or what is your stake). Use a rate that you think is appropriate. You can sell if right away, of course, or wait for a little profit.

Generally, the bot is not going to touch anything beyond the stake. And it will only sell what it bought, not extra.
