### ISSUE TITLE
15m timeframe breaks the strategy

### ISSUE THREAD

**Issue by EgyptianM** [iterativv/NostalgiaForInfinity#239]
Hello,
Thank you for the brilliant strategy.
I'm trying to test it on 15m time frame but when I do that it breaks the whole strategy, why is that?
and how to use it on 15m timeframe?

**Comment by iterativv** [comment]
Hello. It will not work. Because the requirements for BTC informative and how is built. I guess, with some changes is doable. But even if it can work, it's going to just buy a lot more with 15m, that if the market is in uptrend, all good, but if not, it's going to fail.
