### ISSUE TITLE
Entries are in very bad positions which leads to huge loses

### ISSUE THREAD

**Issue by EgyptianM** [iterativv/NostalgiaForInfinity#240]
![image](https://user-images.githubusercontent.com/12565380/186430819-45c7d307-ccbe-45c1-9e3d-6ef1fdf9456e.png)

Red arrows point to entry points according to the strategy, green ones show where it should be.
Does this happen with you or there's something wrong in my configuration 
I'm using latest version of the strategy and I update it immediately when you push a commit.
Those entries make trades take very long time to recover from the lose if they did.

**Comment by iterativv** [comment]
Well, we can't predict the future. There are many calculation that attempts to optimize it, if possible. Plus, those are not losses, the trade exited with profit, as you can see.

**Comment by iterativv** [comment]
Also, are you using the latest NFI ? I don't recognize those trades. KARA, yes. BRISE had several exits. The rest, I am not sure. Or it's a list with more than 70 pairs.

**Comment by EgyptianM** [comment]
We can't predict the future but we can enhance the entry calculations, I hope this is possible.

> Also, are you using the latest NFI ? I don't recognize those trades. KARA, yes. BRISE had several exits. The rest, I am not sure. Or it's a list with more than 70 pairs.

It's a list with more than 70 pairs on Kucoin.

This trade wiped all my profit and made it negative value
![image](https://user-images.githubusercontent.com/12565380/186631248-36a1a74f-dd2d-4256-a99a-cb2d5bb369e7.png)

**Comment by EgyptianM** [comment]
I'm posting my results to help enhance the strategy, I'm testing on small amount of money. 
It's doing very well but didn't expect this amount of stop loss.
Thank you for your work

**Comment by iterativv** [comment]
Yes, well, the new stoploss will fix those at least. Plus, going to drop the trades earlier. -10% or so average, if there are any losses, I think. ZBC I checked it already too on the buy side.

**Comment by taualex** [comment]
@EgyptianM I would avoid trading coins with very low market cap and volume - they can have huge unpredictable swings that no indicator can catch right before it happens. No strategy can prevent that - speaking from experience. DFYN is only 5M market cap.
It's better to trade coins with 200M+ market cap and at least 10M+ in 24h volume. Anything else will have unpredictable results, and most likely cost you in wasted fees and a SL.

**Comment by JhorAVi** [comment]
> @EgyptianM I would avoid trading coins with very low market cap and volume - they can have huge unpredictable swings that no indicator can catch right before it happens. No strategy can prevent that - speaking from experience. DFYN is only 5M market cap. It's better to trade coins with 200M+ market cap and at least 10M+ in 24h volume. Anything else will have unpredictable results, and most likely cost you in wasted fees and a SL.

Can you share your configuration to filter low market cap coins? What do you think of mine?
```
        {
            "method": "PriceFilter",
            "min_price": 0.05,
            "low_price_ratio": 0.01
        }
```

**Comment by EgyptianM** [comment]
> > @EgyptianM I would avoid trading coins with very low market cap and volume - they can have huge unpredictable swings that no indicator can catch right before it happens. No strategy can prevent that - speaking from experience. DFYN is only 5M market cap. It's better to trade coins with 200M+ market cap and at least 10M+ in 24h volume. Anything else will have unpredictable results, and most likely cost you in wasted fees and a SL.
> 
> Can you share your configuration to filter low market cap coins? What do you think of mine?
> 
> ```
>         {
>             "method": "PriceFilter",
>             "min_price": 0.05,
>             "low_price_ratio": 0.01
>         }
> ```

There is no way to filter low market cap coins in Freqtrade bot.

Your approach doesn't filter them.

**Comment by anymus0** [comment]
> There is no way to filter low market cap coins in Freqtrade bot.

I believe you can blacklist specific pairs in the configs [like here](https://github.com/iterativv/NostalgiaForInfinity/blob/main/configs/blacklist-binance.json).
Although manually adding all low market cap coins of an exchange sounds tedious, you could filter out the results with the exchange's API and dump them into the config or copy paste them.

Haven't tested it, just an idea

**Comment by EgyptianM** [comment]
> > There is no way to filter low market cap coins in Freqtrade bot.
> 
> I believe you can blacklist specific pairs in the configs [like here](https://github.com/iterativv/NostalgiaForInfinity/blob/main/configs/blacklist-binance.json). Although manually adding all low market cap coins of an exchange sounds tedious, you could filter out the results with the exchange's API and dump them into the config or copy paste them.
> 
> Haven't tested it, just an idea
> 
> Edit: There are also a few other filter configs [here](https://github.com/iterativv/NostalgiaForInfinity/blob/main/configs/pairlist-volume-binance-usdt.json) like "VolatilityFilter" for example

I mean there is no filter for marketcap in Freqtrade but sure you can blacklist any coin you want manually.
Exchanges doesn't provide marketcap information so the bot needs to get it from out source which is not implemented in Freqtrade.

**Comment by taualex** [comment]
I would either maintain a static list of pairs (this is my approach), and update it once a week/month, or create a python script to get all pairs based on cap and volume once a day/week and dump into the config file. You can use either exchange API or places like CoinMarketCap or CoinGecko

**Comment by iterativv** [comment]
This is too old already. If there are still issue, please, don't hesitate to open a new issue.
