### ISSUE TITLE
Entering coins returning from a pump

### ISSUE THREAD

**Issue by EgyptianM** [iterativv/NostalgiaForInfinity#241]
Again the strategy makes entry points in middle of coin fall back

![image](https://user-images.githubusercontent.com/12565380/187094945-b0cf2684-30a7-471f-96b5-bd9f3a84b1a6.png)

![image](https://user-images.githubusercontent.com/12565380/187094969-ac7b1061-8e57-4fce-acd2-e2f6bebca2f4.png)

Can we avoid this by tracking coins price back for a specific period of time and if there is a huge pump in the price then we avoid those entries?

Is this possible by anyway?

If you need any logs or any more information I'll be happy to provide

![image](https://user-images.githubusercontent.com/12565380/187095132-8a267374-2155-4b5e-bebd-3f013b5d7c15.png)

Strategy version  v11.2.1

**Comment by EgyptianM** [comment]
It worked fine but missed a lot of profit
![image](https://user-images.githubusercontent.com/12565380/187126747-b8c0ea01-f00f-48d4-929f-921a77022209.png)

Can we enhance exits for more profit
I know you are working on it in a daily basis, I'm sharing my results and thoughts with you maybe it will help.
Thank you for this hard and brilliant work.

**Comment by iterativv** [comment]
Yes, at this point, no major features for the current version planned. Fixes and enhancement, of course. Anything else and much more with the next version.

Especially on the sell side. I want to maximize the potential too.

**Comment by EgyptianM** [comment]
@iterativv 
Same issue again
Entering a coin in the middle of fall back of a pump:
![image](https://user-images.githubusercontent.com/12565380/188330592-5de108cc-59f2-4b33-98ab-5268eab26fed.png)

**Comment by EgyptianM** [comment]
![image](https://user-images.githubusercontent.com/12565380/188469845-d251acc2-716d-4a9d-b106-b8bf006d1782.png)

Can you please fix this issue.
It erases the entire profit specially the strategy is rarely trading and missing a lot of potential opportunities.

**Comment by EgyptianM** [comment]
@iterativv Unfortunately strategy is losing money, no profit till now since I used it
Any profit it makes it wipes it and much more.
![image](https://user-images.githubusercontent.com/12565380/189488248-923241c3-e563-4d61-99e6-61accbfeb78e.png)

![image](https://user-images.githubusercontent.com/12565380/189488306-6fcb651f-d44e-40ec-98c3-decdac1225b5.png)

Is it just me or this is happening for you too?
If it's only me can you please just tell me what I'm doing wroni?
I decreased number of coins to only 70.

**Comment by IceyMint** [comment]
Can confirm this is an issue for me as well.

**Comment by EgyptianM** [comment]
I tested it till 476 and it still losing money.
Unfortunately I stopped it.

**Comment by spammik** [comment]
This is still a problem...bot made some nice trades but then one trade wipe it off. It entered here, a coin falling from a pump than keeps falling down.

![image](https://user-images.githubusercontent.com/57185483/199067785-8da9b5fa-8b64-42cb-94b9-44ed8d4fb3ef.png)

![image](https://user-images.githubusercontent.com/57185483/199068046-b41ccb19-383e-4576-b140-d56eddd1cf92.png)

**Comment by nairit** [comment]
Same here
![image](https://user-images.githubusercontent.com/435546/216980719-3d2d291f-7f98-4005-8376-290e684f2640.png)
I am wondering is it possible to avoid early entrance?

**Comment by alex-drocks** [comment]
Guys, I recommand you update your bot to X2. If I'm correct, all your screenshots are from previous version which is in maintenance mode now.

**Comment by iterativv** [comment]
This is too old already. If there are still issue, please, don't hesitate to open a new issue.
