### ISSUE TITLE
Weird stoploss  

### ISSUE THREAD

**Issue by EgyptianM** [iterativv/NostalgiaForInfinity#242]
Hi,
The strategy exited a coin last night with a stoploss of -8.63% where there are other trades which at nearly 30% lose and still open
The most weird thing that the coin recovered to entry point a few hours later.
So why the exit?
![image](https://user-images.githubusercontent.com/12565380/187413138-fcae4803-ef77-466b-ab3c-6b4f6072e70b.png)
 

Close Reason : sell_stoploss_u_e_1_m ( 15 )

![image](https://user-images.githubusercontent.com/12565380/187413912-a9f1280d-027b-4923-bfe6-50e67ca64466.png)

Left green arrow is the entry
red arrow exit
Right green is coin price recovered to entry point in few hours.

Other open trades with way more loss
![image](https://user-images.githubusercontent.com/12565380/187414506-cd6acebb-024b-498f-a9c1-52b848ddfa0a.png)

v11.2.2
If any more info needed I'll be happy to provide.

**Comment by iterativv** [comment]
For new trades, after 28 August, there is a new stop. Just modified, that SUKU probably should not exit.

But yes, going to be like that. Avoid heavy losses. A trade like SUKU is recoverable with 4-5 wins.

**Comment by iterativv** [comment]
Also, from now on, trades will not stay open for too long, maybe 2-3 days if things go well.

But yes, about SUKU too, there was an update, to make the new stop less trigger happy.

The general viewpoint is that though, don't hold losing trades too long, and if losses, then minimize it, to -8% -15%

**Comment by EgyptianM** [comment]
>that SUKU probably should not exit.

This what I thought so I posted it here.

I'll close other trades when it comes to a proper loss.
Thank you very much
