### ISSUE TITLE
No trades for about 2 weeks

### ISSUE THREAD

**Issue by BillyYan13** [iterativv/NostalgiaForInfinity#250]
I've been running the strategy for about 2 weeks and until now no trades happened. I have a stable internet and my PC (Mac) is modern and has no RAM or CPU issues. In the logs I get sometimes this error every few hours.

2022-09-22 12:16:37,293 - freqtrade.rpc.rpc - WARNING -  Could not get rate for pair LDBTC.

I tried to reduce pairs to from 80 to 60 to 40, it didn't work out.

My config.json is:

{
    "max_open_trades": 4,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "dry_run_wallet": 10000,
    "fiat_display_currency": "USD",
    "dry_run": false,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "*****************",
        "secret": "*******************",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
          ".*/USDT"

        ],
        "pair_blacklist": [
          "BNB/.*",
          "BTC/.*",
          "ETH/.*",
          "XMR/.*"

        ]

    },
    "pairlists": [
        {
            "timeframe": "5m",
            "method": "VolumePairList",
            "number_assets": 40,
            "sort_key": "quoteVolume",
            "min_value": 10000,
            "refresh_period": 86400,
            "lookback_period": 7
        }
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "*********",
        "chat_id": "********"
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "***********",
        "CORS_origins": [],
        "username": "***********",
        "password": "*********"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }

}

Thanks a lot in advance!

Edit: Under "pair_whitelist": [
          ".*/USDT"

The star doesn't appear in the code here in the post here, but it's there in the original code.

**Comment by cazzeken** [comment]
Use a dynamic volume-pairlist and try again
https://github.com/iterativv/NostalgiaForInfinity/blob/main/configs/pairlist-volume-binance-usdt.json

**Comment by cazzeken** [comment]
All :-) 
But you can see what they do on the very useful documentation @ https://freqtrade.io. That way, you don't blindly copy stuff, know what you do and can tweak it so you get the results you want.

**Comment by iterativv** [comment]
> > Use a dynamic volume-pairlist and try again https://github.com/iterativv/NostalgiaForInfinity/blob/main/configs/pairlist-volume-binance-usdt.json
> 
> Hello, taking advantage of your answer, should all the methods in the pair list be entered or do I need to choose one of them?

Hi, use the one for your exchange, also important is the blacklist too. Load your config first, then blacklist and pairlist. As -c your_config -c blacklist -c pairlist.

Don't load your config last, because it will overwrite other parameters from blacklist/pairlist.

**Comment by BillyYan13** [comment]
> Use a dynamic volume-pairlist and try again
> https://github.com/iterativv/NostalgiaForInfinity/blob/main/configs/pairlist-volume-binance-usdt.json

Hi. Thanks for the reply. I had this config before and it didn't work out. I modified the config around the time you wrote me, but nothing happened yet. It's been around 24 hours.

Current config.

{
    "max_open_trades": 6,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "dry_run_wallet": 10000,
    "fiat_display_currency": "USD",
    "timeframe": "5m",
    "dry_run": false,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "unfilledtimeout": {
        "entry": 15,
        "exit": 15,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "order_types": {
        "entry": "limit",
        "exit": "limit",
        "emergency_exit": "limit",
        "force_entry": "limit",
        "force_exit": "limit",
        "stoploss": "limit",
        "stoploss_on_exchange": false,
        "stoploss_on_exchange_interval": 60
    },
    "entry_pricing": {
        "price_side": "other",
        "use_order_book": false,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "other",
        "use_order_book": false,
        "order_book_top": 1,
        "price_last_balance": 0.0
    },
    "exchange": {
        "name": "binance",
        "key": "********",
        "secret": "********",
        "ccxt_config": { "enableRateLimit": true },
        "ccxt_async_config": {
                "enableRateLimit": true,
			          "rateLimit": 100
        },
        "pair_whitelist": [

        ],
        "pair_blacklist": [
          ".*(_PREMIUM|BEAR|BULL|HALF|HEDGE|UP|DOWN|[1235][SL])/.*",
			    "(AUD|BRZ|CAD|CHF|EUR|GBP|HKD|IDRT|JPY|NGN|RUB|SGD|TRY|UAH|USD|ZAR)/.*",
			    "(BUSD|CUSD|CUSDT|DAI|PAXG|SUSD|TUSD|USDC|USDN|USDP|USDT|VAI|UST|USTC|AUSD)/.*",
			    "(ACM|AFA|ALA|ALL|APL|ASR|ATM|BAR|CAI|CITY|FOR|GAL|GOZ|IBFK|JUV|LEG|LOCK-1|NAVI|NMR|NOV|PFL|PORTO|PSG|ROUSH|STV|TH|TRA|UCH|UFC|YBO)/.*",
			    "(1EARTH|ILA|BOBA|CTXC|CWAR|HBAR|NMR|OMG|ONG|ARDR|DMTR|MLS|TORN)/.*"

        ]

    },
    "pairlists": [
        {
			"method": "VolumePairList",
			"number_assets": 100,
			"sort_key": "quoteVolume",
			"refresh_period": 1800
		},
		{"method": "AgeFilter", "min_days_listed": 30},
		{
			"method": "RangeStabilityFilter",
			"lookback_days": 3,
			"min_rate_of_change": 0.03,
			"refresh_period": 1800
		},
		{
			"method": "VolatilityFilter",
			"lookback_days": 3,
			"min_volatility": 0.01,
			"max_volatility": 0.75,
			"refresh_period": 43200
		},
        {
            "method": "VolumePairList",
            "number_assets": 70,
            "sort_key": "quoteVolume"
        },
        {"method": "ShuffleFilter"}
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "**********",
        "chat_id": "*********"
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "************",
        "CORS_origins": [],
        "username": "*******",
        "password": "********"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }


}

**Comment by Kleingeldprinz** [comment]
My Bot is working, but my last buy was on September, 19th. So maybe, 24 hours is too short for a waiting window...
