### ISSUE TITLE
Canceling SELL order due to time-out and issues trading coins with small volumes

### ISSUE THREAD

**Issue by BillyYan13** [iterativv/NostalgiaForInfinity#254]
Hi,

Upon existing order cancelling SELL order due to time-out is not actually cancelled on the contrary of cancelling BUY order due to time-out. Although I get a message on my Freqtrade Telegram bot, that the order is cancelled due time out and it does not work. So I must exist the trade manually and delete the trade later from the Freqtrade bot, as /forcesell would not help.

I See this problem while trying to sell coins with lower volumes, as orders will not be filled or partially filled. Is it possible that upon cancelling such trades that the bot sells with "market limit" instead of a "limit order"? Or setting a bit more lower limit immediately, so the order will be filled? I mean it is the only way it manually works. This issue is causing me huge losses by keeping the failed trades unfilled and open. 

Thank you very much in advance!

**Comment by iterativv** [comment]
Hi. This is a bug. I think it sells most of the amount but smaller than 1 USDT remains ? If yes, this is known FT issue. Update your FT, along with NFI.

If the remaining amount is less than 1 USDT, then it's not huge loss, in fact. Just annoying.

**Comment by BillyYan13** [comment]
Hi, no. I reported the other issue related to amount smaller than 1 USD at Freqtrade. I am using the very latest version of both FT and NFI.

No, Ihm talking about larger amounts of money, each trade can reach up to 20-40k. When the bot wants to sell them, most of the time it is a huge number for trading volumes. So the price dips and the bot can't adjust fast to the drop and I keep "unwillingly" holding the coins. I lost because of that about 7k in one for example about 3 weeks ago.

**Comment by iterativv** [comment]
> Hi, no. I reported the other issue related to amount smaller than 1 USD at Freqtrade. I am using the very latest version of both FT and NFI.
> 
> No, Ihm talking about larger amounts of money, each trade can reach up to 20-40k. When the bot wants to sell them, most of the time it is a huge number for trading volumes. So the price dips and the bot can't adjust fast to the drop and I keep "unwillingly" holding the coins. I lost because of that about 7k in one for example about 3 weeks ago.

If it's very large amount, then yes, maybe there isn't enough volume to sell. Consider to break it to multiple bots, instead ?

**Comment by BillyYan13** [comment]
> If it's very large amount, then yes, maybe there isn't enough volume to sell. Consider to break it to multiple bots, instead ?

Breaking it into multiple bots will neither that practical, nor profitable. I am not trying to impose changes on the bots, but suggesting an improvement to deal with bigger trades, to keep the bot's sustainability and profitability for even much bigger trades. I am asking for feature to quickly adapt to small trading market volumes and sell with a little bit less than market price to guarantee a successful, although less profitable, trade. You know better of course. I hope that you will be taking my suggestion in consideration. Thank you very much!

**Comment by iterativv** [comment]
> > If it's very large amount, then yes, maybe there isn't enough volume to sell. Consider to break it to multiple bots, instead ?
> 
> Breaking it into multiple bots will neither that practical, nor profitable. I am not trying to impose changes on the bots, but suggesting an improvement to deal with bigger trades, to keep the bot's sustainability and profitability for even much bigger trades. I am asking for feature to quickly adapt to small trading market volumes and sell with a little bit less than market price to guarantee a successful, although less profitable, trade. You know better of course. I hope that you will be taking my suggestion in consideration. Thank you very much!

Have you tried market orders ? With limit, you can use orderbook and top 4-6 entry.

**Comment by BillyYan13** [comment]
> Have you tried market orders ? With limit, you can use orderbook and top 4-6 entry.

Thank you once again for the reply. I already use 6 entries. How can I change to market orders instead of limit orders?

This is my config:

"order_types": {
        "entry": "limit",
        "exit": "limit",
        "emergency_exit": "limit",
        "force_entry": "limit",
        "force_exit": "limit",
        "stoploss": "limit",
        "stoploss_on_exchange": false,
        "stoploss_on_exchange_interval": 60
    },
    "entry_pricing": {
        "price_side": "other",
        "use_order_book": false,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "other",
        "use_order_book": false,
        "order_book_top": 1,
        "price_last_balance": 0.0
    },

**Comment by iterativv** [comment]
All right, first, you can try to change all limit to market. There is chance of slippage, but the sell should go on, even if a bit lower, depends on the current action and volume.

**Comment by BillyYan13** [comment]
> All right, first, you can try to change all limit to market. There is chance of slippage, but the sell should go on, even if a bit lower, depends on the current action and volume.

Good idea. I did change it and try it out. Let's see how this will turn out. Thank you!

**Comment by iterativv** [comment]
If you have other questions, you can also join the discord server server to discuss it. Thanks !
