### ISSUE TITLE
Generating profits in Backtest but losses in LIVE Mode

### ISSUE THREAD

**Issue by hamiz-ahmed** [iterativv/NostalgiaForInfinity#255]
Hi,
I recently deployed the strategy in live mode with volume trading pairs.
The strategy, in the results of around 24 hrs, has made a loss of over 2% and has still loss trades opened.
I backtested the strategy during the same time frame and same coin pairs and according to backtesting results, the strategy should have made a profit of 1% and would have closed the trades.

The pairs I have tested are
SUN/USDT
ACH/USDT

Following are the results of backtesting:

![image](https://user-images.githubusercontent.com/21131088/196031085-7c57cb6d-4514-4f33-8804-e3a6ce223933.png)
![image](https://user-images.githubusercontent.com/21131088/196031115-e455edeb-bfd1-4b3f-b4dc-d1a511c90ef5.png)

![image](https://user-images.githubusercontent.com/21131088/196031047-0e59d9eb-3e80-4975-bab1-e2430d82124c.png)

Following are the results of live testing so far:

![image](https://user-images.githubusercontent.com/21131088/196031186-4bf62dc1-8e4b-4bd2-871c-26d41ba3395f.png)

Any idea, why does this happen?

**Comment by iterativv** [comment]
First, those trades are open. But also closed for most, to my knowledge. You had any sell timeouts ? QI is open. ACH and SUN closed yesterday.

**Comment by iterativv** [comment]
For ACH I got 0.0129 open rate and 0.01305 close rate. Maybe your open is a lot higher that this ? Or a sell time out occurred. You sold anything so far ?

**Comment by iterativv** [comment]
Also, from the trades ID, you had SUN ID = 2 that closed with 2-3% profit ? Patience for QI. ACH, probably you missed the sell. But, providing all go well, it will attempt again.

**Comment by hamiz-ahmed** [comment]
I did not have any sell timeouts. SUN closed, ACH and QI are still open with over 10% loss now. It opened further two positions on QI and ACH, so now the stake amount is even more.
Nothing has been sold so far. Yes, SUN made a profit but overall, I am at over 5% loss and for the same backtesting period, I am still supposed to get profits.

**Comment by iterativv** [comment]
> I did not have any sell timeouts. SUN closed, ACH and QI are still open with over 10% loss now. It opened further two positions on QI and ACH, so now the stake amount is even more. Nothing has been sold so far. Yes, SUN made a profit but overall, I am at over 5% loss and for the same backtesting period, I am still supposed to get profits.

Yes, if you check QI is as supposed to be. ACH closed for most. I am not sure why yours not. QI is open in backtest too. Note: not anymore, because there were changes, I did not like the QI trade much.

Wait on those, there is stop lower, but there is good chance to make it.

The real problem is why ACH is still open, probably you get a high open rate. It closed for here, for example. QI is still open. And QI was open in backtest, with the version you used in live. You test is SUN & ACH, not QI and ACH.

**Comment by iterativv** [comment]
Also, at the bottom of the main page, there is a link to discord. If you use it, join the server, if you like. To discuss anything there.

**Comment by hamiz-ahmed** [comment]
Do you think that the trade not closing, could be a bug in Freqtrade?

**Comment by EgyptianM** [comment]
I tested it for over than a month and I have the databases with me,
Last version was 475 then I stopped it and switched to another strategy.
It doesn't make any profit in live trading, actually it loses money up to 30% of the capital.
It makes a lot of low profit trades them wipes them all with 2 or 3 stop loss trades.
I reduced number of coins to 50 then 40 to avoid shit coins and it's the same.
Unfortunately I stopped it and I'm searching for another strategy.
See #241

**Comment by iterativv** [comment]
> I tested it for over than a month and I have the databases with me, Last version was 475 then I stopped it and switched to another strategy. It doesn't make any profit in live trading, actually it loses money up to 30% of the capital. It makes a lot of low profit trades them wipes them all with 2 or 3 stop loss trades. I reduced number of coins to 50 then 40 to avoid shit coins and it's the same. Unfortunately I stopped it and I'm searching for another strategy. See #241

There is major reworks the last 3-4 weeks ... try in in dry run. There is nothing that even comes near to NFI.

Sure, the market is not great. But give it a chance with the new reworks.

**Comment by iterativv** [comment]
> I tested it for over than a month and I have the databases with me, Last version was 475 then I stopped it and switched to another strategy. It doesn't make any profit in live trading, actually it loses money up to 30% of the capital. It makes a lot of low profit trades them wipes them all with 2 or 3 stop loss trades. I reduced number of coins to 50 then 40 to avoid shit coins and it's the same. Unfortunately I stopped it and I'm searching for another strategy. See #241

Also, while working on current X, I am planning the next version. There will be new buy signals, potential for big/huge wins. Trade the top20 coins or so daily. And much more. But you can set a dry run with the current if you like. Even in this market, you going to notice the difference. I don't think there is a chance to not have profit every week. Even if not, example pretty bad conditions, there should be break even or minimal loss (-1 -2%) for that week.

**Comment by hamiz-ahmed** [comment]
I think the amount of refining being performed in the strategy kind of overfits and not generalize the strategy. That's why it works great during backtests but fails in live modes

**Comment by iterativv** [comment]
> I think the amount of refining being performed in the strategy kind of overfits and not generalize the strategy. That's why it works great during backtests but fails in live modes

These latest changes, don't change anything on the core of the buy signals. It's just protections, as where not to buy. So, not over fitting at all.

As for your trades, just wait, my guess is that those going to close with profit.

But some trades can take few hours, maybe days. it doesn't mean we have always trades that last minutes.

**Comment by iterativv** [comment]
Also, the tests confirm live trades. I backtest the live trades. Of course, there are changes, if I notice a trade is not optimal.

**Comment by iterativv** [comment]
> Lets see if it closes on profit. I will inform you if it does. For now, I am testing another instance on dry run. Lets see if the strategy works there

I know about QI. But ACH closed for most others. This is different for you, it happens some times. From what I see both look OK now. Just patience.

**Comment by EgyptianM** [comment]
> Do you think that the trade not closing, could be a bug in Freqtrade?

Which version do you use?
I encountered something like that, the bot missed some exit signals I don't know why.
Some times it misses 2 or 3 exits in a row.
No timeout orders so it's weird.
I'm using latest version 2022.9.1

**Comment by hamiz-ahmed** [comment]
> > Do you think that the trade not closing, could be a bug in Freqtrade?
> 
> Which version do you use? I encountered something like that, the bot missed some exit signals I don't know why. Some times it misses 2 or 3 exits in a row. No timeout orders so it's weird. I'm using latest version 2022.9.1

I am using the same so it could be the same issue

**Comment by iterativv** [comment]
> > > Do you think that the trade not closing, could be a bug in Freqtrade?
> > 
> > 
> > Which version do you use? I encountered something like that, the bot missed some exit signals I don't know why. Some times it misses 2 or 3 exits in a row. No timeout orders so it's weird. I'm using latest version 2022.9.1
> 
> I am using the same so it could be the same issue

No, this is unlikely. What it happened some times, is to sell normal, but FT still calculates that the order is open (with less than 1 USDT stake). In that case, you can check the exchange if there are open orders and delete that trade, if all good.

**Comment by iterativv** [comment]
Note: some others had ACH, that closed overnight. With updated NFI. QI is also near to profit. Sure, this took longer that normal, but profit in the end. Please, join the discord server to discuss to it further, thanks.

**Comment by hamiz-ahmed** [comment]
I am still facing loss. My loss has mounted to over 20%.
In live mode, the strategy doesn't perform at all, even in the dry run.
