### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by Spixmaster** [iterativv/NostalgiaForInfinity#261]
All tests fail which assume "NostalgiaForInfinityNext.py" in the root directory.

**Comment by iterativv** [comment]
Hi. You mean the auto tests. At this point, Next is too old, last update was more than a year ago.

**Comment by Spixmaster** [comment]
Yes. The tests which are executed by running `pytest` in the root directory. I just packaged this software for the [AUR](https://aur.archlinux.org/packages/python-nostalgiaforinfinity) and need to run the tests. Unfortunately, I cannot run the tests at the moment.

**Comment by iterativv** [comment]
I am going to look into it.

**Comment by iterativv** [comment]
This is too old already. If there are still issue, please, don't hesitate to open a new issue.
