### ISSUE TITLE
What is the difference between NostalgiaForInfinityX and NostalgiaForInfinityX2?

### ISSUE THREAD

**Issue by BillyYan13** [iterativv/NostalgiaForInfinity#262]
This question might sound like a naive one. However, are they to be used together and how? Or do they function together together?
What should I use as a strategy in the docker-compose.yml file? NostalgiaForInfinitX or NostalgiaForInfinitX2?

**Comment by iterativv** [comment]
Hi. If you start now, best to use X2. That is rewrite from scratch. But it's under heavy development, so make sure you update often.

The objective is no long duration trades, no deep losses.

**Comment by nittanygeek** [comment]
What will happen to those trades if you just switch strats?

**Comment by BillyYan13** [comment]
> Hi. If you start now, best to use X2. That is rewrite from scratch. But it's under heavy development, so make sure you update often.
> 
> 
> 
> The objective is no long duration trades, no deep losses.

Thanks for the reply. I tried using NFIX2 my Freqtrade doesn't run it at. I get an error message in logs.

Operating system: ____ Mac
Python Version: _____ (Python 3.10.7)
CCXT version: _____ (2.4.60)
Freqtrade Version: ____ (`docker-compose run --rm freqtrade -V, 22.12)

**Comment by BillyYan13** [comment]
> > Hi. If you start now, best to use X2. That is rewrite from scratch. But it's under heavy development, so make sure you update often.
> > 
> > 
> > 
> > The objective is no long duration trades, no deep losses.
> 
> Thanks for the reply. I tried using NFIX2, however my Freqtrade doesn't run it at all. I get an error message in logs.
> 
> Operating system: ____ Mac
> Python Version: _____ (Python 3.10.7)
> CCXT version: _____ (2.4.60)
> Freqtrade Version: ____ (`docker-compose run --rm freqtrade -V, 22.12)

The strategy NFIX2 is still not working. Freqtrade V- 23.1

**Comment by Cristy94** [comment]
What about X3, X4?

Could you add in the readme a short description of which ones are "best" or still under development?
