### ISSUE TITLE
For every trades stoploss and initial stoploss is -99%

### ISSUE THREAD

**Issue by matthieu-hm** [iterativv/NostalgiaForInfinity#267]
Hello,

Maybe I don't understand, how you're recommending to configure stoploss, or how the stoploss work.

From what I understood, the strategy should set the stoploss value itself. But for every trades stoploss and initial stoploss is always -99%.

I have a trade that reached 20% loss, I'm surprised it's not tried to exit.

Is it normal ? The stoploss is handle by the strategy ?

Strategy: `NostalgiaForInfinityX2`

```json
{
  "dry_run": true,
  "max_open_trades": 3,
  "stake_currency": "USDT",
  "stake_amount": "unlimited",
  "tradable_balance_ratio": 0.99,
  "fiat_display_currency": "USD",
  "cancel_open_orders_on_exit": false,
  "trading_mode": "spot",
  "margin_mode": "",
  "unfilledtimeout": {
    "entry": 15,
    "exit": 15,
    "exit_timeout_count": 0,
    "unit": "minutes"
  },
  "entry_pricing": {
    "price_side": "same",
    "use_order_book": true,
    "order_book_top": 1,
    "price_last_balance": 0.0,
    "check_depth_of_market": {
      "enabled": false,
      "bids_to_ask_delta": 1
    }
  },
  "exit_pricing": {
    "price_side": "same",
    "use_order_book": true,
    "order_book_top": 1
  },
  "exchange": {
    "name": "binance",
    "key": "",
    "secret": "",
    "ccxt_config": {},
    "ccxt_async_config": {},
    "pair_blacklist": [
      "(BNB)/.*",
      ".*(_PREMIUM|BEAR|BULL|HALF|HEDGE|UP|DOWN|[1235][SL])/.*",
      "(AUD|BRZ|CAD|CHF|EUR|GBP|HKD|IDRT|JPY|NGN|RUB|SGD|TRY|UAH|USD|ZAR)/.*",
      "(BUSD|CUSD|CUSDT|DAI|PAXG|SUSD|TUSD|USDC|USDN|USDP|USDT|VAI|UST|USTC|AUSD)/.*",
      "(ACM|AFA|ALA|ALL|ALPINE|APL|ASR|ATM|BAR|CAI|CHZ|CITY|FOR|GAL|GOZ|IBFK|JUV|LEG|LOCK-1|NAVI|NMR|NOV|PFL|PSG|ROUSH|STV|TH|TRA|UCH|UFC|YBO)/.*",
      "(1EARTH|ILA|BOBA|CTXC|CWAR|HBAR|NMR|OMG|ONG|ARDR|DMTR|MLS|TORN|ANC|LUNA|BTS|QKC|COS|ACA|FTT|SRM|YFII|SNM|BNX|WAVES)/.*"
    ]
  },
  "pairlists": [
    {
      "method": "VolumePairList",
      "number_assets": 100,
      "sort_key": "quoteVolume",
      "refresh_period": 1800
    },
    { "method": "AgeFilter", "min_days_listed": 30 },
    {
      "method": "PriceFilter",
      "low_price_ratio": 0.003
    },
    {
      "method": "SpreadFilter",
      "max_spread_ratio": 0.005
    },
    {
      "method": "RangeStabilityFilter",
      "lookback_days": 3,
      "min_rate_of_change": 0.03,
      "refresh_period": 1800
    },
    {
      "method": "VolatilityFilter",
      "lookback_days": 3,
      "min_volatility": 0.01,
      "max_volatility": 0.75,
      "refresh_period": 43200
    },
    {
      "method": "VolumePairList",
      "number_assets": 65,
      "sort_key": "quoteVolume"
    },
    { "method": "ShuffleFilter" }
  ],
  "edge": {
    "enabled": false,
    "process_throttle_secs": 3600,
    "calculate_since_number_of_days": 7,
    "allowed_risk": 0.01,
    "stoploss_range_min": -0.01,
    "stoploss_range_max": -0.1,
    "stoploss_range_step": -0.01,
    "minimum_winrate": 0.6,
    "minimum_expectancy": 0.2,
    "min_trade_number": 10,
    "max_trade_duration_minute": 1440,
    "remove_pumps": false
  },
  "db_url": "sqlite:////freqtrade/user_data/tradesv3.sqlite",
  "bot_name": "freqtrade1",
  "initial_state": "running",
  "force_entry_enable": false,
  "internals": {
    "process_throttle_secs": 5
  },
  "logfile": "/freqtrade/user_data/logs/freqtrade.log"
}
```

![Capture d’écran du 2023-02-13 11-54-59](https://user-images.githubusercontent.com/16086894/218439894-1dc0b3e3-5b89-43d7-910e-11e7b4f065e0.png)

Thank you

**Comment by iterativv** [comment]
Hello,
NFI is using specialized sells to stop the trades at a loss, not that.
The HIGH trade, while not optimal, is not quitting yet.
As always, try to update when there is new NFI version. I am improving it constantly.

**Comment by dida1990** [comment]
The stoploss of -99% just says, that it will be disabled and handled by custom strategies.
In terms of bad trades that can happen from time to time I saw the stoploss strategies kicking in at ~ -25%.

Whenever a bad trade happens, the coder will analyze what went wrong and add new ways to prevent those bad trades from happening again.

All in all a great strategy that's worth trying out in a dry run!

**Comment by dida1990** [comment]
1. No, NFIX2 is already superior to all other previous versions.

2.  Yes, however we just decide between NFIX and X2 (NFIX2) these days, as the other legacy strategies are no longer maintained.

3. X2 is designed to be a complete rework of NFIX with completely new/improved entry and exit strategies.
Main focus is safety: Better leave out an entry on a promising uptrend then dealing with a slow bleeding coin.

Currently the coder is nearly done with reworking the entry signals and results are looking promising. We got a lot of people on discord already running this strategy live. Feel free to join :)

**Comment by matthieu-hm** [comment]
Ok thank you for the info
