### ISSUE TITLE
No trading points for three days

### ISSUE THREAD

**Issue by owlswaper** [iterativv/NostalgiaForInfinity#278]
I executed the strategy but it doesn't show me any entry and exit points.
I have been checking it for three days now and it is like this in all currencies.
Is it because of the high win rate of the strategy that enters the trade at few points or is there a problem?

![Screenshot from 2023-03-18 08-28-59](https://user-images.githubusercontent.com/117394732/226085916-6877b59d-7e14-410b-bca7-08f2684b8a35.png)

**Comment by Ace167** [comment]
Same here

**Comment by SebTechDevelopment** [comment]
It's not doing anything for me..

**Comment by godshades** [comment]
@owlswaper how about this bro, i got the same issue
@meisamsafavi hi, does this relate to server spec ?

**Comment by meisamsafavi** [comment]
@godshades 
Hi,
My problem was happening duo to low hardware specs of my VPS.
Try Vultr's high frequency or Hetzner's Ashborn AMD base VPS.
