### ISSUE TITLE
Updating Strategy

### ISSUE THREAD

**Issue by Kleingeldprinz** [iterativv/NostalgiaForInfinity#280]
Hi iterativv,
thank you for all you hard work and the permanent updates to make this good strategy even better!
I have a question for the update strategy (so the strategy to update the strategy :P ).

I am updating the raw strat file from github every 12 hours, independent, if it is released or not (this file: https://github.com/iterativv/NostalgiaForInfinity/blob/main/NostalgiaForInfinityX2.py)
Or is it better, to download only the released strategy? 
You are updating the file more often, then the releases. So which way is better?
Thank you very much!

**Comment by iterativv** [comment]
Hi. Either should work. Releases is fine.

**Comment by Kleingeldprinz** [comment]
Thank you!
