### ISSUE TITLE
Backtesting results

### ISSUE THREAD

**Issue by ngtianxun** [iterativv/NostalgiaForInfinity#281]
Hi, I wonder how you achieved so much profit in the backtest (as seen in your commit comments), would you mind sharing your settings (config.json, which pairs are selected to trade/not to trade, etc tunings) for your backtesting? Thank you.

This is the config.json I'm using (Based on the config.json in https://github.com/iterativv/NostalgiaForInfinity/blob/main/configs/exampleconfig.json, https://github.com/iterativv/NostalgiaForInfinity/blob/main/configs/blacklist-kucoin.json and https://github.com/iterativv/NostalgiaForInfinity/blob/main/configs/pairlist-volume-kucoin-usdt.json):
{
    "max_open_trades": 6,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "unfilledtimeout": {
        "entry": 5,
        "exit": 20,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "order_types": {
        "entry": "limit",
        "exit": "limit",
        "emergency_exit": "limit",
        "force_entry": "limit",
        "force_exit": "limit",
        "stoploss": "limit",
        "stoploss_on_exchange": false,
        "stoploss_on_exchange_interval": 60
    },
    "entry_pricing": {
        "price_side": "other",
        "use_order_book": false,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "other",
        "use_order_book": false,
        "order_book_top": 1,
        "price_last_balance": 0.0
    },
    "exchange": {
        "name": "kucoin",
        "key": "",
        "secret": "",
        "password": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
        ],
        "pair_blacklist": [
            "KCS/.*",
            ".*(3L|3S|5L|5S)/.*",
            "(AUD|BRZ|CAD|CHF|EUR|GBP|HKD|IDRT|JPY|NGN|RUB|SGD|TRY|UAH|USD|ZAR)/.*",
            "(BUSD|CUSD|CUSDT|DAI|PAXG|SUSD|TUSD|USDC|USDN|USDP|USDT|VAI|UST|USDD|USDJ|USTC|AUSD)/.*",
            "(ACM|AFA|ALA|ALL|ALPINE|APL|ASR|ATM|BAR|CAI|CITY|FOR|GAL|GOZ|IBFK|JUV|LEG|LOCK-1|NAVI|NMR|NOV|PFL|PORTO|PSG|ROUSH|STV|TH|TRA|UCH|UFC|YBO)/.*",
            "(1EARTH|ILA|MEM|AMPL|BOBA|CWAR|OMG|XYM|POLX|CARR|SKEY|KLV|KRL|KOK|DMTR|CHMB|CPOOL|MLS|RBS|SRBS|SYLO|VR|KARA|LUNA|SRBP|PSL|AI|QKC|EPK|BAX|UQC|ZBC|PLATO|ACA|XCN|MC|FTT|SRM|PRMX|SWP|XWG|PIAS|KICKS|TIME|BNX|WEMIX|HI.*|ALBT|ANC|CIX100|GLCH|MIR|XTAG|CELT|TEM|ZKT|MVP|ADB|AXPR|H2O|FT|BNC|BNX|STG|RLY|HNT|MARS4|DRGN|WXT|ROSN|KYL|FRR|STARLY)/.*"
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 100,
            "sort_key": "quoteVolume",
            "refresh_period": 1800
        },
        {"method": "AgeFilter", "min_days_listed": 3},
        {
            "method": "PriceFilter",
            "low_price_ratio": 0.003
        },
        {
            "method": "SpreadFilter",
            "max_spread_ratio": 0.0075
        },
        {
            "method": "RangeStabilityFilter",
            "lookback_days": 3,
            "min_rate_of_change": 0.03,
            "refresh_period": 1800
        },
        {
            "method": "VolatilityFilter",
            "lookback_days": 3,
            "min_volatility": 0.01,
            "max_volatility": 0.75,
            "refresh_period": 43200
        },
        {
            "method": "VolumePairList",
            "number_assets": 60,
            "sort_key": "quoteVolume"
        },
        {"method": "ShuffleFilter"}
    ],
    "telegram": {
        "enabled": true,
        "token": "6195703028:AAF-8mxD7ZzM6zYsRV8gKIUueiwdCJSFCak",
        "chat_id": "6162748974"
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "450236386b190d5c59e3beb046673602f3b3e22804d8a7d1993e6f1a5d25570d",
        "ws_token": "vAobRkTnuPpHaO-E8iMzPVdoLcBh_Qwt0Q",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": "123"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": true,
    "internals": {
        "process_throttle_secs": 5
    }
}

**Comment by iterativv** [comment]
Hi, the auto tests is for X1 currently. Going to change to X2 later.

Don't mind those too much, it's for comparison between version mostly. The configs and lists are there, as you see it.

**Comment by ngtianxun** [comment]
I see. It would be good if it is the X2 backtesting (Using Freqtrade's backtest function). Thanks

**Comment by Mandark-droid** [comment]
In my fork you can find the back testing results for X2. https://github.com/Mandark-droid/NostalgiaForInfinity

**Comment by ngtianxun** [comment]
That's valuable, thank you!

**Comment by iterativv** [comment]
If there are still issue, please, don't hesitate to open a new issue.
