### ISSUE TITLE
pairlist files in config contain VolumePairList twice

### ISSUE THREAD

**Issue by klara31** [iterativv/NostalgiaForInfinity#294]
Most pairlist files in the config directory contain the key VolumePairList twice. Is this for a specific reason or an error?

**Comment by iterativv** [comment]
Hi. The filter apply in order. The first volume collects 100 pairs, the following filters remove some pairs, perhaps and finally we end with the number of pairs from the second volume list.

**Comment by klara31** [comment]
I didn't know that. Thanks!
