### ISSUE TITLE
 ERROR - Unexpected error NostalgiaForInfinityX3.bot_loop_start() missing 1 required positional argument: 'current_time' calling 

### ISSUE THREAD

**Issue by simwai** [iterativv/NostalgiaForInfinity#297]
Hey @iterativv,
First of all, I wanna thank you for this awesome project.
Next, I had an issue to run it with my freqtrade.
I used my own config, which worked on my other strategies.

The error happened when I wanted to run a backtest with that command:
`freqtrade backtesting -i 5m --strategy-list NostalgiaForInfinityX3 --logfile ./user_data/logs/NostalgiaForInfinityX3.txt --config config_mfiemawavetrend.json --breakdown week`

```
2023-06-09 15:44:45,456 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error NostalgiaForInfinityX3.bot_loop_start() missing 1 required positional argument: 'current_time' calling 
<bound method NostalgiaForInfinityX3.bot_loop_start of <NostalgiaForInfinityX3.NostalgiaForInfinityX3 object at 0x000001D27F44D210>>
Traceback (most recent call last):
  File "G:\Downloads\GitHub\freqtrade\freqtrade\strategy\strategy_wrapper.py", line 27, in wrapper
    return f(*args, **kwargs)
```

Any idea how to solve that?

**Comment by iterativv** [comment]
Hi, sorry for the late reply. If you have not figured it yet, try to update your FT.

**Comment by iterativv** [comment]
This should be fixed. If not, try to use a more recent FT version.  Thanks.
