### ISSUE TITLE
bitvavo: which blacklist and pairlist?

### ISSUE THREAD

**Issue by klara31** [iterativv/NostalgiaForInfinity#299]
I am wondering which blacklist and pairlist the bitvavo users over here are using?
Would it be possible to add these in the config as well?

**Comment by iterativv** [comment]
Hi, pairlist you can use any, same to USDT lists, let's say gate. Also for blacklist, start with the gate one.

**Comment by iterativv** [comment]
This is too old already. If there are still issue, please, don't hesitate to open a new issue.
