### ISSUE TITLE
How does this protection work?

### ISSUE THREAD

**Issue by EgyptianM** [iterativv/NostalgiaForInfinity#302]
Sorry for the inconvenience, can you explain how this works and what does it mean?

![image](https://github.com/iterativv/NostalgiaForInfinity/assets/12565380/75859eb3-a262-4762-9411-832e2bfd1ef9)

What does the `close_max_#`  and other conditions mean?
If you can explain this section in short it will be very appreciated.
Thank you  very much

**Comment by iterativv** [comment]
This is the max in the last 48 candles. In this case, we don't want more than 30% drop from that max (that in that case is quite a lot).

**Comment by iterativv** [comment]
This is too old already. If there are still issue, please, don't hesitate to open a new issue.
