### ISSUE TITLE
NFIX, X2 and X3

### ISSUE THREAD

**Issue by pomwtin** [iterativv/NostalgiaForInfinity#310]
Hello,

since in readme it is not mentioned I would kindly ask what is different between NFIX, NFIX2 and NFIX3?
Are those just the latest (X3) and two older versions?

Thanks in advance,
M

**Comment by iterativv** [comment]
Hi,

at this point best to use X3, the one that receives updates and new features. There is natural progress, plus some major features. X2 added partial buys & sells. X3 if there is a dip on a trade drops all allowed stake and keeps the trade open to make it back with rebuys.

**Comment by pomwtin** [comment]
Thank you for explanation. Much appreciated.
