### ISSUE TITLE
how to get file using wget

### ISSUE THREAD

**Issue by godshades** [iterativv/NostalgiaForInfinity#319]
Hi, in my vps i want update the strategy using wget
but the file i downloaded is losing format (no indent)
how to fix this or what script i should use

**Comment by iterativv** [comment]
It's the raw file, open the file here, then you will notice a "raw" button.

X3 for example: https://raw.githubusercontent.com/iterativv/NostalgiaForInfinity/main/NostalgiaForInfinityX3.py
