### ISSUE TITLE
Exit trade too soon

### ISSUE THREAD

**Issue by godshades** [iterativv/NostalgiaForInfinity#355]
Hi, I use X4 strategy and see this log, it it normal, why it's exit too soon xD

```
✳ Binance: Exited HOOK/USDT:USDT (#188)
Profit: 0.11% (profit: 0.00973273 USDT / 0.010 USD)
Enter Tag: 21 
Exit Reason: exit_pump_u_0 ( 21 )
Direction: Long
Leverage: 5.0
Amount: 41.90000000
Open Rate: 1.02150000
Exit Rate: 1.02210000
Duration: 0:00:23 (0.4 min)
```

**Comment by iterativv** [comment]
> Hi, I use X4 strategy and see this log, it it normal, why it's exit too soon xD

Hi, yes. In this case it was too low. So preferred to exit, than risk it.

Changes planned, for exit rework, plus futures optimization. Note, futures for NFI is recent too.
