### ISSUE TITLE
Stake amount for pair is too small

### ISSUE THREAD

**Issue by godshades** [iterativv/NostalgiaForInfinity#363]
> Stake amount for pair YGG/USDT is too small (1.9478778880275 < 5.25), adjusting to 5.25.
> Adjusted stake amount for pair YGG/USDT is more than 30% bigger than the desired stake amount of (1.94787789 * 1.3 = 2.53224125) < 5.25), ignoring trade.

hi, can some one help me explain what does this mean, i see this log but when i forcelong via tele it still ok

> Long signal found: about create a new trade for YGG/USDT with stake_amount: 6.4929262934250005

**Comment by meesvw** [comment]
Like it says, the amount you want to trade is too small. Some trading platforms require that you trade a minimum amount of money. In this case your bot is compensating by increasing the amount it will trade.

You can solve this issue by either reducing the amount of open trades inside your config.json. Or you can give the bot more money so it will divide your money with bigger chunks for example: 1000/4=250 per trade.
