### ISSUE TITLE
[Err] not supported between instances of 'NoneType' and 'float' 

### ISSUE THREAD

**Issue by godshades** [iterativv/NostalgiaForInfinity#365]
> freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error '>=' not supported between instances of 'NoneType' and 'float' calling <bound method NostalgiaForInfinityX4.custom_exit of <NostalgiaForInfinityX4.NostalgiaForInfinityX4 object at 0xffff66dd07d0>>
> Traceback (most recent call last):
>   File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
>     return f(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^
>   File "/freqtrade/user_data/strategies/NostalgiaForInfinityX4.py", line 5088, in custom_exit
>     sell, signal_name = self.exit_normal(
>                         ^^^^^^^^^^^^^^^^^
>   File "/freqtrade/user_data/strategies/NostalgiaForInfinityX4.py", line 730, in exit_normal
>     sell, signal_name = self.exit_long_dec(
>                         ^^^^^^^^^^^^^^^^^^^
>   File "/freqtrade/user_data/strategies/NostalgiaForInfinityX4.py", line 3127, in exit_long_dec
>     and (last_candle["cti_20_1d"] >= 0.50)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: '>=' not supported between instances of 'NoneType' and 'float'

i just see this log

**Comment by m-kubik** [comment]
I have same problem, usually when CEX is listing a new coin. I guess it's due to the fact historical candle data are missing. I'm wondering when this happens if strategy s till running fine for already opened trades or all is failing?

Local workaround here is to put a new coin to blacklist. However I think this should be fixed in script somehow

**Comment by iterativv** [comment]
Yes, confirm for which pair it is. It's best to use age filter, at least 3 days. See configs dir, pairlists & blacklist there. As well as example config.

**Comment by godshades** [comment]
@iterativv in my case it was XAI/USDT on binance. i already using age filter 3 days

**Comment by m-kubik** [comment]
> Yes, confirm for which pair it is. It's best to use age filter, at least 3 days. See configs dir, pairlists & blacklist there. As well as example config.

thank you. I did not know about age filter - that's working great
