### ISSUE TITLE
duplicate code in buy_condition_1 logic

### ISSUE THREAD

**Issue by abc112116** [iterativv/NostalgiaForInfinity#37]
line 3288 and 3289 appear to be the same 
https://github.com/iterativv/NostalgiaForInfinity/blob/2cbc142e40d0b4fe264d95aaa2a05091bc52c8a6/NostalgiaForInfinityNext.py#L3288
https://github.com/iterativv/NostalgiaForInfinity/blob/2cbc142e40d0b4fe264d95aaa2a05091bc52c8a6/NostalgiaForInfinityNext.py#L3289

**Comment by iterativv** [comment]
Thanks, will be fixed shortly.

**Comment by lobap** [comment]
It comes fixed with the PR i have just submitted few minutes ago.

**Comment by eSeR1805** [comment]
Fixed through 2c555c4c4948fee7d649351ea02dd7e232d179c1.
