### ISSUE TITLE
When bot will DCA?

### ISSUE THREAD

**Issue by godshades** [iterativv/NostalgiaForInfinity#371]
Hi, i have setting: "grinding_enable": true,  "position_adjustment_enable": true
and have this pair: T/USDT     2 weeks  -32.01%
Does anyone know when this will DCA my pair, i'm using X4 latest
i have set stake_amount fixed to 6, does this make bot can't DCA

**Comment by andrasmining** [comment]
If it makes sense, it does "DCA". look at the method `adjust_trade_position()` what are the prerequisites for adjusting the order.
If you think it should have been triggered add some proof please. But because it is -32%, does not justify a DCA at all.

**Comment by iterativv** [comment]
That is 6 USDT ? Which exchange ? Probably it can't rebuy, because there is min stake limitations.
