### ISSUE TITLE
Inquiry about the NostalgiaForInfinityX4 strategy: Principles, Applicability to Futures Contracts, Recommended Settings, Maximum Leverage, Stop-loss Logic, etc

### ISSUE THREAD

**Issue by aixuedegege** [iterativv/NostalgiaForInfinity#400]
Is there any explanation about the NostalgiaForInfinityX4 strategy? I would like to understand its principles. Can it be used for futures contracts? Are there any recommended settings? How much leverage can be applied? What is the logic behind the stop-loss, etc.?

**Comment by iterativv** [comment]
Hi.

Well, a lot of the entries are based on mean reversion, but not limited to that. It strives to pick accurate entries, but after a trade open - that know starts with half the normal stake - there are tools to manage it, in case of dips. Basically, unless totally collapse, it can handle all trades.

And yes, futures supported, of course, extra careful there if live, only funds you are comfortable with. The leverage is 3x

There is configs dir on the repo here, with exampleconfig, secrets, blacklists and volume pairlists.

**Comment by aixuedegege** [comment]
ok i will read the cool strat. good job!
