### ISSUE TITLE
trategy analysis took 98.05s, more than 25% of the timeframe (75.00s)

### ISSUE THREAD

**Issue by AlexiaChen** [iterativv/NostalgiaForInfinity#407]
my environment:

- WSL 2 on windows 11
- CPU is AMD Ryzen 7 7840HS
- 16 logical processors already assigned to WSL2 from .wslconfig file

<img width="577" alt="image" src="https://github.com/user-attachments/assets/860c6c28-ac70-4c9b-bf8e-4d48a8d901a2">

<img width="675" alt="image" src="https://github.com/user-attachments/assets/2df14ba9-259f-4fe0-895c-dff2ada52050">

freqtrade UI logs show the warning:

```txt
WARNING freqtrade.freqtradebot - Strategy analysis took 98.05s, more than 25% of the timeframe (75.00s). This can lead to delayed orders and missed signals.Consider either reducing the amount of work your strategy performs or reduce the amount of pairs in the Pairlist.
```

I already reduced pairs from 100 to 75. but this warning message is always exists,   is it my CPU is slow?? it must be joking

```json
{
"pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 75,
            "sort_key": "quoteVolume",
            "refresh_period": 1800
        },
        { "method": "FullTradesFilter" },
        { "method": "AgeFilter", "min_days_listed": 30 },
        {
            "method": "PriceFilter",
            "low_price_ratio": 0.003
        },
        {
            "method": "SpreadFilter",
            "max_spread_ratio": 0.005
        },
        {
          "method": "VolumePairList",
          "number_assets": 75,
          "sort_key": "quoteVolume"
        }
    ],
}

```

**Comment by AlexiaChen** [comment]
continuely reduce to 60  seems not received this warning

**Comment by tolgakaratas** [comment]
make it 50 or 40, try to reduce step by step. Your processor and network total computing time should be less.
