### ISSUE TITLE
ho_to_raw_codemod.py generates invalid raw strategy - missing commas after buy_protection_params values

### ISSUE THREAD

**Issue by lobap** [iterativv/NostalgiaForInfinity#41]
ho_to_raw_codemod.py generates invalid raw strategy

missing commas after buy_protection_params values which produces an invalid strategy:
![image](https://user-images.githubusercontent.com/778506/127756809-2f89c168-645d-4776-a219-f6af843c2d8d.png)

**Comment by anasyusef** [comment]
This should now be fixed with PR #43

**Comment by eSeR1805** [comment]
Fixed by @anasyusef. Thanks!
