### ISSUE TITLE
İnteresting price action and De-Risk

### ISSUE THREAD

**Issue by taygun08** [iterativv/NostalgiaForInfinity#437]
Hello, After holding a position for a long time, they significantly reduced it just before the volume increased. This is the first time I’ve seen de-risk triggered after a 8-day dry run. What exactly does this mean?

info mesage:
"De-risk MASK/USDT:USDT | Rate: 2.4104 | Stake amount: 6.125633333333333 | Profit (stake): -5.969254279358996 | Profit: -14.51%"

![image](https://github.com/user-attachments/assets/0b1a82ac-0491-434d-8341-39c038e6b886)
![image](https://github.com/user-attachments/assets/88f5281d-9201-4008-b8cd-e1e9176ad8b7)

**Comment by iterativv** [comment]
Hello, first thing, I don't recognize this MASK trade exactly or there was a MASK that exited already in profit.

This is to prevent a big damage, but also attempt to recover it after with grinding. Smaller entries and exits of these with 1.8% + profit.

Currently it will take 40-50 grind exits to complete it.

**Comment by iterativv** [comment]
> @iterativv Yes, there are two timeouts. If it had exited on the first one, the position would already appear closed. It went into timeout because it was running in dry-run mode. The reason is that the price started to drop right after the signal, and it couldn't return to the same level to get a closing confirmation. This issue won’t occur in live mode. From which line in the strategy file are the De-Risk rules written? I'd like to review them.

It's function long_adjust_trade_position_no_derisk() ... at the end it's the de-risk too.
