### ISSUE TITLE
NFI X5 "v15.1.206" Exit strategy for NFI X5 on a losing trade.

### ISSUE THREAD

**Issue by Marc-BXL** [iterativv/NostalgiaForInfinity#440]
My NFIX5 strategy entered a bad trade, and it doesn’t seem to want to exit. It’s been over 24 hours, and at times it has dropped to -13%. I’m wondering how the strategy is supposed to react – does this behavior seem normal to you?
![Capture2](https://github.com/user-attachments/assets/1d0da15a-da99-48e7-afd7-b72b796c2e5f)
![Capture](https://github.com/user-attachments/assets/1afc7082-b50a-48f9-826b-2a23cd55c596)

**Comment by iterativv** [comment]
Also, likely with this ALPACA, it went into what we call "de-risk". This means exited most of the stake already. Now it will recover it with grinding, it will take days, but incrementally it should recover, while picking other trades.

**Comment by Marc-BXL** [comment]
Thank you for this information 👍

**Comment by iterativv** [comment]
This answered it. If any more questions, please, don't hesitate to open a new issue. Thank you.
