### ISSUE TITLE
Risk Management Anomaly

### ISSUE THREAD

**Issue by taygun08** [iterativv/NostalgiaForInfinity#441]
I am running a dry-run with a number higher than the recommended max trade amount.
I have reached the max trade and there is no more cash left to manage the positions :D
Can this situation occur with 5 max trades?
How does cash management work?

![image](https://github.com/user-attachments/assets/4c27c04a-eb54-4d3e-b819-207a1e8788da)
![image](https://github.com/user-attachments/assets/0409b8d7-55c8-4143-8156-ad51b6cc4362)

**Comment by iterativv** [comment]
Hi. ALPACA likely de-risked already, that means it exited most stake, but the min. Going to recover it with grinding.

With the other trades, they approaching break even currently, so it's a matter of waiting, there is no need to change anything at the moment.

**Comment by iterativv** [comment]
> The first thing is that it needs balance to do grinding. Does it normally set aside a portion of the balance for this or is this normal?

No, if grinds needed, as in after de-risk, likely there is funds available. Because the de-risk is going to exit all, but the min required.
