### ISSUE TITLE
NostalgiaForInfinity/user_data/strategies/NostalgiaForInfinityNext.py due to 'invalid syntax (NostalgiaForInfinityNext.py, line 1)'

### ISSUE THREAD

**Issue by 20flint12** [iterativv/NostalgiaForInfinity#453]

**Comment by 20flint12** [comment]
freqtrade - ERROR - Impossible to load Strategy '../NostalgiaForInfinityX5'. This class does not exist or contains Python code errors.

**Comment by iterativv** [comment]
If you use docker, then that is a link, not the real py file. Either use `--strategy-path main_nfi_repo_here` or move the py file to where you want it to load from.

**Comment by 20flint12** [comment]
Ok. I thought that link will work. Sorry for stupid issue.

**Comment by iterativv** [comment]
No worries, if anything else don't hesitate to open another issue !
