### ISSUE TITLE
Missed .env file in repo

### ISSUE THREAD

**Issue by gabrin** [iterativv/NostalgiaForInfinity#55]
https://github.com/iterativv/NostalgiaForInfinity/blob/main/.env

**Comment by fmhc** [comment]
You need to set up your own .env file in which you define the environment variables used in the docker-compose script. Guess we could have an improvement here to have a sample .env file

**Comment by potens1** [comment]
https://github.com/iterativv/NostalgiaForInfinity/issues/6

**Comment by eSeR1805** [comment]
How each configure and run freqtrade is outside of the scope of this repo
