### ISSUE TITLE
Fine tuning question

### ISSUE THREAD

**Issue by abanchev** [iterativv/NostalgiaForInfinity#57]
All this fine tuning and optimizations, how are they tested, one or multiple time periods, i am a bit concerned regarding overfitting the values to the backtest period.

**Comment by iterativv** [comment]
Tests on multiple periods (Last 4 months, last month, March 2020), exchanges (Binance, kucoin) and stakes (USDT, BUSD). The first objective is not to cause harm (losses).

**Comment by abanchev** [comment]
Okay nice to know that, is there a way to do distributed backtesting or hyperopt? Maybe having a system that splits the work between volunteer worker machines? Can hyperopt be split into smaller chunks?

**Comment by iterativv** [comment]
Hyperopt is not effective with NFI. Maybe for additions to determine the basic values and then continue on from that.

But testing, sure. If anyone is interested, there are aspects of the strategy that require to determine the limits of specific values. Tests should occur with many pairs and multiple time ranges, however.

**Comment by Charlie-Root** [comment]
Can't we (largely) use Github for this? Within my own Freqtrade repo I have created a CI/CD that starts Freqtrade build and a backtest.

**Comment by eSeR1805** [comment]
HO params were removed completely. Can we close this?
