### ISSUE TITLE
TypeError: unsupported operand type(s) for &: 'bool' and 'float'

### ISSUE THREAD

**Issue by jasonbhart** [iterativv/NostalgiaForInfinity#58]
At several places in the code a bool flag is referenced in the dataframe (in the below error message it is "last_candle['sma_200_dec_20_1h']" but is some how now recognized as such for bitwise AND operations.  

It looks like the fix is to either switch to using 'and' instead of '&' in the stringing together of multiple logical conditions, or modify these type of bool flag checks to make the result an explicit bool, for example:
last_candle['sma_200_dec_20_1h'] == True

Here is an example of error spam which occurs when the buy condition is evaluated during execution.  This is just an example, as this type of situation exists several places in the code and can be triggered whenever the prior conditions in the logic statement are true.
`2021-08-05 01:24:49,111 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error unsupported operand type(s) for &: 'bool' and 'float' calling <bound method NostalgiaForInfinityNext.custom_sell of <NostalgiaForInfinityNext.NostalgiaForInfinityNext object at 0x7f96e84ac5e0>>
Traceback (most recent call last):
  File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/NostalgiaForInfinityNext.py", line 2938, in custom_sell
    sell, signal_name = self.sell_trail_main(current_profit, last_candle, max_profit)
  File "/freqtrade/NostalgiaForInfinityNext.py", line 2655, in sell_trail_main
    elif (self.sell_trail_profit_max_3.value > current_profit > self.sell_trail_profit_min_3.value) & (max_profit > (current_profit + self.sell_trail_down_3.value)) & (last_candle['sma_200_dec_20_1h']):
TypeError: unsupported operand type(s) for &: 'bool' and 'float'`

**Comment by iterativv** [comment]
Yes, it's trivial to change to _and_ operator for those. There is a chance of missing data, providing that it's backtest and the trade occurred at the start of the time range.

Does it happen with the stable Freqtrade or the develop ?

Will get to it shortly.

**Comment by jasonbhart** [comment]
I've only be using Freqtrade develop when I run into this.  I havent tested with stable.  Should I?

**Comment by iterativv** [comment]
No, it's OK. Develop should do it. I will get to that shortly.

**Comment by iterativv** [comment]
Is this fixed with the latest changes ? Still appears ?

**Comment by jasonbhart** [comment]
I'll do some testing but in reviewing the recent code changes this SHOULD be resolved.  Will close and re-open if by chance I see it again in the future.
