### ISSUE TITLE
The `.env` file is missing from the repository

### ISSUE THREAD

**Issue by potens1** [iterativv/NostalgiaForInfinity#6]
So the variables to set the backtesting with Docker are not set and the `docker-compose run` results in an error since flags are called without values, i.e.:
```
usage: freqtrade backtesting [-h] [-v] [--logfile FILE] [-V] [-c PATH] [-d PATH] [--userdir PATH] [-s NAME] [--strategy-path PATH] [-i TIMEFRAME] [--timerange TIMERANGE] [--data-format-ohlcv {json,jsongz,hdf5}] [--max-open-trades INT]
                             [--stake-amount STAKE_AMOUNT] [--fee FLOAT] [-p PAIRS [PAIRS ...]] [--eps] [--dmmp] [--enable-protections] [--dry-run-wallet DRY_RUN_WALLET] [--strategy-list STRATEGY_LIST [STRATEGY_LIST ...]] [--export {none,trades}]
                             [--export-filename PATH]
freqtrade backtesting: error: argument --timerange: expected one argument

```

**Comment by Ughuuu** [comment]
Was introduced by this PR https://github.com/iterativv/NostalgiaForInfinity/pull/4. It seems that the `.env` is ignored by `.gitignore`

**Comment by potens1** [comment]
Could we not just set defaults values into the `docker-compose.yml` file, so, env is not needed, if there, it will be taken in account, and if shell override, it overadies the defaults from `docker-compose.yml`, and end `.env` ?
i.e: `{MAX_OPEN_TRADES:-5}` (it means if the variable is not set, set it to 5, not -5)
