### ISSUE TITLE
Use websocket for binance

### ISSUE THREAD

**Issue by tolgakaratas** [iterativv/NostalgiaForInfinity#67]
Please consider about using binance websocket
there is an example here : https://github.com/TomtomEh/freqtrade-websocket

explained by developer :
Using websockets you will get the pair information pushed from binance servers as soon as they are computed. For instance, while testing using about 100 pairs, freqtrade took almost one minute to start computing the new candle, while using this approcach in 3s all pairs were already processed.

Using talipp reduce the computation power required, since data are update by only adding the contribution of the new candle to the already computed data. While freqtrade computes the indicators on their integrity and by default for 1000 timeframes.

**Comment by s0undt3ch** [comment]
also, NFI does not calculate indicators between candles, so, even though data would be realtime, indicators would still be calculated only every 5 minutes....

but i can be totaly wrong here....

**Comment by fmhc** [comment]
can we switch NFI to 1m to make this work?

**Comment by eSeR1805** [comment]
https://github.com/abanchev/binance-proxy
NFI can't work on 1m. Logic is not built for that timeframe and depending on system it might take more that 1m to process all indicators, logic for all pairs

**Comment by s0undt3ch** [comment]
That proxy is interesting

**Comment by s0undt3ch** [comment]
@eSeR1805 are you using it?

**Comment by abanchev** [comment]
I am using it, right now reading 100 pairs candle data takes between 1 and 2 seconds, and then processing it takes 25 seconds more.

**Comment by s0undt3ch** [comment]
Would it be able to handle two bots one UDT and the other BUSD?

**Comment by abanchev** [comment]
there should not be any issues, also it can be easily tested using dryrun.
there may be a limit on how many pairs it can handle, but so far i havent reached it

**Comment by eSeR1805** [comment]
@s0undt3ch Not using it currently. That delay usually works in our favor 😄 
Closing this as there is a solution from @abanchev and this is not strictly speaking a strategy-related topic.
