### ISSUE TITLE
buy signal 5, EMA default variable mismatch

### ISSUE THREAD

**Issue by koradiyakaushal** [iterativv/NostalgiaForInfinity#9]
in buy_05_close_above_ema_slow_len, default value is 36, but in the populate indicator there is no ema_36

https://github.com/iterativv/NostalgiaForInfinity/blob/main/NostalgiaForInfinityNext.py#L236

so which value will come instead of 36 or we will need to add ema_36 in the populate indicator?

**Comment by iterativv** [comment]
85f4555 closes this. No need to add another EMA, plus is not used currently, for buy 5.
